<script>
  import Icon from "./Icon.svelte";

  let {
    result,
    error,
    busy,
    format,
    lastPath,
    emptyHint,
    showExport = true,
    caption = "",
    onFormat,
    onSave,
    onCopyImage,
    onCopyText,
    onReveal,
  } = $props();

  const LEVEL = {
    good: { icon: "check", label: "Scans correctly" },
    risky: { icon: "alert", label: "Scans, with caveats" },
    bad: { icon: "stop", label: "Will not scan reliably" },
  };

  let verdict = $derived(result?.verdict ?? null);
  let level = $derived(verdict ? LEVEL[verdict.level] : null);
</script>

<aside class="preview">
  <div class="plate" class:empty={!result}>
    {#if result}
      <!-- Trusted: this string is generated by our own Rust renderer, and it
           is the exact document that save writes to disk. -->
      {@html result.svg}
    {:else if error}
      <p class="placeholder error-text">{error}</p>
    {:else}
      <p class="placeholder">{emptyHint}</p>
    {/if}
  </div>

  {#if result && verdict}
    <div class="verdict {verdict.level}">
      <Icon name={level.icon} />
      <span>{level.label}</span>
    </div>
    {#if verdict.notes.length}
      <ul class="notes">
        {#each verdict.notes as note}
          <li>{note}</li>
        {/each}
      </ul>
    {/if}

    <p class="meta">
      {#if caption}{caption} &middot; {/if}{result.modules} &times; {result.modules} modules
      &middot; PNG {result.sizePx} px
    </p>

    <!-- The format choice stays visible in every mode, because batch export
         uses it too even though it runs its own button. -->
    <div class="segmented" role="group" aria-label="Export format">
      <button
        type="button"
        aria-pressed={format === "svg"}
        onclick={() => onFormat("svg")}>SVG</button>
      <button
        type="button"
        aria-pressed={format === "png"}
        onclick={() => onFormat("png")}>PNG</button>
    </div>

    {#if showExport}
    <button class="btn save" disabled={busy} onclick={onSave}>
      <Icon name="download" />
      Save {format.toUpperCase()}
    </button>

    <div class="secondary">
      <button class="text-button" disabled={busy} onclick={onCopyImage}>
        <Icon name="copy" /> Copy image
      </button>
      <button class="text-button" disabled={busy} onclick={onCopyText}>
        Copy contents
      </button>
    </div>

    {#if lastPath}
      <button class="text-button reveal" onclick={onReveal}>
        <Icon name="folder" /> Show in folder
      </button>
    {/if}
    {/if}
  {/if}
</aside>

<style>
  .preview {
    flex: 0 0 300px;
    border-left: 1px solid var(--hairline);
    background: var(--bg-panel);
    padding: 18px 20px 24px;
    display: flex;
    flex-direction: column;
    align-items: stretch;
    gap: 12px;
    overflow-y: auto;
  }

  /* A hairline round the plate keeps a white-on-white code visible in light
     mode, where the QR background and the panel would otherwise merge. */
  .plate {
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 260px;
    padding: 14px;
    border: 1px solid var(--hairline-strong);
    border-radius: 10px;
    background: var(--preview-bg);
  }
  .plate.empty {
    border-style: dashed;
  }
  /* The SVG carries its own pixel width; override it so a large export size
     does not blow out the panel. The viewBox keeps it exact at any size. */
  .plate :global(svg) {
    width: 100%;
    height: auto;
    max-width: 232px;
    display: block;
  }

  .placeholder {
    font-size: 12px;
    color: var(--text-faint);
    text-align: center;
    max-width: 200px;
    line-height: 1.5;
  }
  .error-text {
    color: var(--bad);
  }

  .verdict {
    display: flex;
    align-items: center;
    gap: 7px;
    font-size: 12px;
    font-weight: 600;
  }
  .verdict.good {
    color: var(--good);
  }
  .verdict.risky {
    color: var(--warn);
  }
  .verdict.bad {
    color: var(--bad);
  }

  .notes {
    list-style: none;
    display: flex;
    flex-direction: column;
    gap: 6px;
    font-size: 12px;
    line-height: 1.45;
    color: var(--text-soft);
  }

  .meta {
    font-size: 12px;
    color: var(--text-faint);
    font-variant-numeric: tabular-nums;
  }

  .segmented {
    align-self: flex-start;
  }

  .save {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
  }

  .secondary {
    display: flex;
    gap: 4px;
    margin-left: -8px;
  }
  .secondary button,
  .reveal {
    display: inline-flex;
    align-items: center;
    gap: 6px;
  }
  .reveal {
    align-self: flex-start;
    margin-left: -8px;
  }
</style>
